swagger: '2.0'
schemes:
  - http
host: xkcd.com
basePath: /
info:
  description: 'Webcomic of romance, sarcasm, math, and language.'
  title: XKCD
  version: 1.0.0
  x-apisguru-categories:
    - media
  x-logo:
    url: 'https://api.apis.guru/v2/cache/logo/http_imgs.xkcd.com_static_terrible_small_logo.png'
  x-origin:
    - format: swagger
      url: 'https://raw.githubusercontent.com/APIs-guru/unofficial_openapi_specs/master/xkcd.com/1.0.0/swagger.yaml'
      version: '2.0'
  x-preferred: true
  x-providerName: xkcd.com
  x-tags:
    - humor
    - comics
  x-unofficialSpec: true
externalDocs:
  url: 'https://xkcd.com/json.html'
securityDefinitions: {}
produces: 
  - application/json
consumes: 
  - application/json
  
paths:

  /info.0.json:
    get:
      operationId: xkcd_getComicForToday
      description: |
        Fetch current comic and metadata.
      responses:
        '200':
          description: OK
          schema:
            type: string
  