pool:
  name: Hosted VS2017
  demands: npm

steps:
- task: Npm@1
  displayName: 'Install autorest@beta'
  inputs:
    command: custom
    verbose: false
    customCommand: 'install -g "@autorest/autorest"'

- powershell: './AutoRestUpgradeTest.ps1 -Configuration'
  pwsh: true
  workingDirectory: 'tests-upgrade'
  displayName: VerifyUpgrade