pool:
  name: Hosted VS2017
  demands: npm

steps:
- task: Npm@1
  displayName: 'Install autorest@beta'
  inputs:
    command: custom
    verbose: false
    customCommand: 'install -g "@autorest/autorest"'

- task: PowerShell@2
  displayName: Verify Upgrade
  inputs:
    targetType: inline
    script: './AutoRestUpgradeTest.ps1 -AllowList'
    workingDirectory: 'tests-upgrade'
    failOnStderr: true